---
- name: Check existing install
  register: amtool_version_check
  failed_when: false
  changed_when: false
  check_mode: false
  ansible.builtin.shell: "{{ amtool_install_directory }}/amtool --version 2>&1"
  tags:
    - amtool

- name: Fact version change
  when:
    - amtool_version_check.stdout_lines is defined
    - amtool_version not in amtool_version_check.stdout_lines[0]
  ansible.builtin.set_fact:
    amtool_version_changed: true
  tags:
    - amtool

- name: Download release tarball
  when:
    - amtool_version_changed
  ansible.builtin.unarchive:
    src: "{{ amtool_download }}"
    dest: "{{ amtool_extract_directory }}"
    remote_src: true
    owner: "{{ amtool_owner }}"
    group: "{{ amtool_group }}"
  tags:
    - amtool

- name: Copy downloaded binaries
  when:
    - amtool_version_changed
    - not ansible_check_mode
  loop:
    - amtool
  ansible.builtin.copy:
    src: "{{ amtool_extract_directory }}/alertmanager-{{ amtool_version }}.linux-{{ amtool_arch }}/{{ item }}"
    dest: "{{ amtool_install_directory }}/{{ item }}"
    remote_src: true
    owner: "{{ amtool_owner }}"
    group: "{{ amtool_group }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - amtool

- name: Remove install directory
  ansible.builtin.file:
    path: "{{ amtool_extract_directory }}/alertmanager-{{ amtool_version }}.linux-{{ amtool_arch }}"
    state: absent
  tags:
    - amtool

...
